[book]
authors = ["The appliedzkp team"]
language = "en"
multilingual = false
src = "src"
title = "AppliedZKP's zkEVM Documentation"

[preprocessor]

# [preprocessor.katex]
# throw-on-error = true
# trust = false

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

# [output.katex]

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
